### ISSUE TITLE
Generator crashing

### ISSUE THREAD

**Issue by eriksaulnier** [davidhellmann/generator-dhBoilerplate#17]
When I attempt to run the generator with "yo dhboilerplace" I get the following error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

ReferenceError: gitInfo is not defined
    at child.askFor (C:\Users\erik\AppData\Roaming\npm\node_modules\generator-dhboilerplate\app\index.js:229:26)
    at Object.<anonymous> (C:\Users\erik\AppData\Roaming\npm\node_modules\generator-dhboilerplate\node_modules\yeoman-generator\lib\base.js:439:23)
    at C:\Users\erik\AppData\Roaming\npm\node_modules\generator-dhboilerplate\node_modules\run-async\index.js:25:25
    at C:\Users\erik\AppData\Roaming\npm\node_modules\generator-dhboilerplate\node_modules\run-async\index.js:24:19
    at C:\Users\erik\AppData\Roaming\npm\node_modules\generator-dhboilerplate\node_modules\yeoman-generator\lib\base.js:440:9
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

I've reinstalled npm/yeoman/the generator multiple times without any luck, any idea what could be going on?

**Comment by davidhellmann** [comment]
Do you have Git installed? @SirAlternate

**Comment by davidhellmann** [comment]
Please try again @SirAlternate
