### ISSUE TITLE
Error on gulp init (Prototyping Option)

### ISSUE THREAD

**Issue by djmtype** [davidhellmann/generator-dhBoilerplate#3]
Installing this generator for the first time. 
Receiving this error: 

```
Requiring external module babel-register
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-twig-up-to-date'
at Function.Module._resolveFilename (module.js:469:15)
 at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/spinline/Sites/thegen/gulp/tasks/templates.js:3:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/spinline/Sites/thegen/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/spinline/Sites/thegen/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

Is babel-register something that needs to be installed and configured separately?

**Comment by davidhellmann** [comment]
Ah sorry, I fix that ASAP! Thanks @djmtype

**Comment by davidhellmann** [comment]
Is fixed now: 
https://github.com/davidhellmann/generator-dhBoilerplate/commit/c2b76d674c80e5984c2d072f49e928152fc45b5d
