### ISSUE TITLE
yo dhboilerplate

### ISSUE THREAD

**Issue by dmzone** [davidhellmann/generator-dhBoilerplate#53]
*********
npm -v 5.0.4
*********

AppData\Roaming\npm\node_modules\generator-dhboilerplate\generators\app\index.js:71
    async initializing() {
          ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by davidhellmann** [comment]
Where is the message? Within the YO process or afterwards?

**Comment by davidhellmann** [comment]
Pushed a small update. Tried it here now and works fine.
